### ISSUE TITLE
Fix GitHub Actions build

### ISSUE THREAD

**Issue by PatrickRWright** [SwissClinicalTrialOrganisation/secuTrialR#201]
**Describe the bug**
GutHub Actions are currently failing and need to be fixed.

**Comment by aghaynes** [comment]
This should fix the mac error...
https://github.com/r-lib/actions/issues/78

```
      - name: Install XQuartz on macOS
        if: runner.os == 'macOS'
        run: brew cask install xquartz
```

**Comment by PatrickRWright** [comment]
As expected the `tidyr` issue has resolved itself. For Windows and Ubuntu a `pdflatex` related error remains. i.e. we probably need to specify that `pdflatex` is needed somewhere in the yaml file.

**Comment by aghaynes** [comment]
Super!

is it worth adding ubuntu-latest to the set of builds?

**Comment by aghaynes** [comment]
Here's a couple of links that might be useful for the tex issue...
https://github.com/r-lib/actions/tree/master/setup-tinytex
https://github.com/r-lib/actions/issues/54

**Comment by PatrickRWright** [comment]
I think we can add all builds that are possible as long as they don't create unreasonable issues. I won't be able to look closer for the next few weeks though.

**Comment by aghaynes** [comment]
of possible use... install latex packages...

  - name: Install latex packages
        run: |
          tlmgr install oberdiek epstopdf-pkg epstopdf grfext gettitlestring environ trimspaces etoolbox upquote babel-english pgf xcolor algorithms relsize tocbibind appendix tocloft enumitem listings tcolorbox 
          tlmgr update --self --all --no-auto-install

**Comment by aghaynes** [comment]
question regarding failing links_secutrial example posted here:
https://community.rstudio.com/t/github-actions-fails-with-tc/65639

**Comment by aghaynes** [comment]
seems to be an issue with R4.0... \donttest examples seem to be being tested...
https://community.rstudio.com/t/r-cmd-check-r-4-0-0-now-runs-donttest-how-to-proceed-with-long-running-examples/64493
